#! /bin/sh

case $1 in
    start)
        cd /lib/modules/$(uname -r)/extra
        echo "Starting scull module"
        /usr/bin/scull_load
        echo "Starting faulty module"
        /usr/bin/module_load faulty

        echo "Starting hello module"
        modprobe hello
        ;;
    stop)
        cd /lib/modules/$(uname -r)/extra
        echo "Stopping scull module"
        /usr/bin/scull_unload
        echo "Stopping faulty module"
        /usr/bin/module_unload faulty
        
        echo "Stopping hello module"
        rmmod hello
        ;;
    *)
        echo "Usage: $0 {start|stop}"
        exit 1
        ;;
esac

exit 0